version: '3.8'
services:
  agentic-ai:
    build: .
    container_name: agentic-ai
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./uploads:/app/uploads
    command: uv pip run src/main.py
